#to update techdemo image:
#rm -rf log/* && sudo docker build --tag=dimitrydimitry/techdemo . && sudo docker push dimitrydimitry/techdemo
#docker pull dimitrydimitry/techdemo

techdemo:
  container_name: techdemo
  build: .
  #image: "dimitrydimitry/techdemo"
  expose:
    - "3000"
  ports:
    - "3002:3000"
  environment:
    - "PORT=3000"
    - "RAILS_ENV=development"
    - "TERM=xterm"
  env_file: .env
  volumes:
    - .:/techdemo/    
  command:
    "bash -c -l 'service mysql start &&
                 bundle install &&
                 rake db:create &&
                 rake db:migrate &&
                 rm -rf /techdemo/tmp/* &&
                 rails s -b 0.0.0.0'"
  mem_limit: 4000m